alias: Klima Wohnzimmer
description: ''
trigger:
  - platform: template
    id: start_klima
    value_template: >-
      {{ states('sensor.time').replace(':', '') | int % 2 == 0 and 
      states('sensor.wohnzimmer_thermostat_temperature') | round(0) | float(0) >
      states('input_number.climate_wohnzimmer_temperature_threshold') |
      float(30) and is_state('climate.wohnzimmer', 'off') }}
  - platform: template
    id: stop_klima
    value_template: >-
      {{ states('sensor.time').replace(':', '') | int % 2 == 0 and 
      states('sensor.wohnzimmer_thermostat_temperature') | float(30) <=
      states('input_number.climate_wohnzimmer_temperature_threshold') | float(0)
      and is_state('climate.wohnzimmer', 'cool') }}
  - platform: template
    id: update_temp
    value_template: >-
      {{ state_attr('climate.wohnzimmer', 'temperature') | float !=
      states('input_number.climate_wohnzimmer_temperature') | float and
      is_state('climate.wohnzimmer', 'cool') and
      states('input_number.climate_wohnzimmer_temperature') | float(0) > 0 and
      state_attr('climate.wohnzimmer', 'temperature') | float(0) > 0 }}
    for: '00:00:01'
condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id: start_klima
        sequence:
          - service: switch.turn_on
            data: {}
            target:
              entity_id: switch.klimaanlage
          - delay: '00:00:30'
          - service: climate.set_hvac_mode
            data:
              hvac_mode: cool
            target:
              entity_id: climate.wohnzimmer
          - service: climate.set_temperature
            data:
              temperature: >-
                {{ states('input_number.climate_wohnzimmer_temperature') |
                float(23) }}
              hvac_mode: cool
            target:
              entity_id: climate.wohnzimmer
          - service: climate.set_fan_mode
            data:
              fan_mode: auto
            target:
              entity_id: climate.wohnzimmer
          - service: climate.set_swing_mode
            data:
              swing_mode: 'on'
            target:
              entity_id: climate.wohnzimmer
      - conditions:
          - condition: trigger
            id: stop_klima
        sequence:
          - service: climate.set_hvac_mode
            data:
              hvac_mode: 'off'
            target:
              entity_id: climate.wohnzimmer
          - delay: '00:05:00'
          - service: switch.turn_off
            data: {}
            target:
              entity_id: switch.klimaanlage
      - conditions:
          - condition: trigger
            id: update_temp
        sequence:
          - service: climate.set_temperature
            data:
              temperature: >-
                {{ states('input_number.climate_wohnzimmer_temperature') |
                float(23) }}
              hvac_mode: cool
            target:
              entity_id: climate.wohnzimmer
mode: single
